// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcWFnGa3x9lxfi5yK0pvnZU4cEW1nLENo',
    appId: '1:103767202646:web:ee85cf24e18863ffd294f7',
    messagingSenderId: '103767202646',
    projectId: 'xchange-fbe78',
    authDomain: 'xchange-fbe78.firebaseapp.com',
    storageBucket: 'xchange-fbe78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5czo4nUf3_4T9VhtCZenalbHofW8Quq4',
    appId: '1:103767202646:android:8b9e7cedb4e375d6d294f7',
    messagingSenderId: '103767202646',
    projectId: 'xchange-fbe78',
    storageBucket: 'xchange-fbe78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZZDkrWuwVGrnIEC16fRVtxBjqTdNvlY',
    appId: '1:103767202646:ios:5e0c83c3d5b6ab81d294f7',
    messagingSenderId: '103767202646',
    projectId: 'xchange-fbe78',
    storageBucket: 'xchange-fbe78.firebasestorage.app',
    iosClientId: '103767202646-j102p981r01kna41fsdqhc48g89pcnh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.xchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ZZDkrWuwVGrnIEC16fRVtxBjqTdNvlY',
    appId: '1:103767202646:ios:5e0c83c3d5b6ab81d294f7',
    messagingSenderId: '103767202646',
    projectId: 'xchange-fbe78',
    storageBucket: 'xchange-fbe78.firebasestorage.app',
    iosClientId: '103767202646-j102p981r01kna41fsdqhc48g89pcnh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.xchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcWFnGa3x9lxfi5yK0pvnZU4cEW1nLENo',
    appId: '1:103767202646:web:71a792efed8b1072d294f7',
    messagingSenderId: '103767202646',
    projectId: 'xchange-fbe78',
    authDomain: 'xchange-fbe78.firebaseapp.com',
    storageBucket: 'xchange-fbe78.firebasestorage.app',
  );
}
